# Generated by Django 3.2.8 on 2021-10-24 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_auto_20211024_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount_of_upvotes',
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='voted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
